version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=auth-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
      - JWT_KEY=your_jwt_key
      - NATS_CLIENT_ID=auth
      - NATS_URL=http://nats-streaming:4222
      - NATS_CLUSTER_ID=smartdine
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - auth-postgres
      - nats-streaming
      - redis

  menu:
    build:
      context: .
      dockerfile: menu/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://menu-mongo:27017/menu
      - JWT_KEY=your_jwt_key
      - NATS_CLIENT_ID=menu-${HOSTNAME}
      - NATS_URL=http://nats-streaming:4222
      - NATS_CLUSTER_ID=smartdine
    depends_on:
      - menu-mongo
      - nats-streaming

  cart:
    build:
      context: .
      dockerfile: cart/Dockerfile
    ports:
      - "3004:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NATS_CLIENT_ID=cart-${HOSTNAME}
      - NATS_URL=http://nats-streaming:4222
      - NATS_CLUSTER_ID=smartdine
    depends_on:
      - redis
      - nats-streaming

  orders:
    build:
      context: .
      dockerfile: orders/Dockerfile
    ports:
      - "3002:3000"
    environment:
      - SQL_URI=postgres://postgres:postgres@orders-postgres:5432/orders
      - JWT_KEY=your_jwt_key
      - NATS_CLIENT_ID=orders-${HOSTNAME}
      - NATS_URL=http://nats-streaming:4222
      - NATS_CLUSTER_ID=smartdine
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - orders-postgres
      - redis
      - nats-streaming

  payments:
    build:
      context: .
      dockerfile: payments/Dockerfile
    ports:
      - "3003:3000"
    environment:
      - SQL_URI=postgres://postgres:postgres@payments-postgres:5432/payments
      - JWT_KEY=your_jwt_key
      - STRIPE_KEY=your_stripe_key
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NATS_CLIENT_ID=payments-${HOSTNAME}
      - NATS_URL=http://nats-streaming:4222
      - NATS_CLUSTER_ID=smartdine
    depends_on:
      - payments-postgres
      - redis
      - nats-streaming

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3050:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost
    depends_on:
      - auth
      - menu
      - orders
      - payments

  # PostgreSQL instance for auth service
  auth-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data

  # PostgreSQL instance for payments service
  payments-postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payments
    volumes:
      - payments-postgres-data:/var/lib/postgresql/data

  # PostgreSQL instance for orders service
  orders-postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
    volumes:
      - orders-postgres-data:/var/lib/postgresql/data

  # MongoDB instances for other services
  menu-mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - menu-mongo-data:/data/db

  # NATS Streaming server
  nats-streaming:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [
      "-p",
      "4222",
      "-m",
      "8222",
      "-hbi",
      "5s",
      "-hbt",
      "5s",
      "-hbf",
      "2",
      "-SD",
      "-cid",
      "smartdine"
    ]
  
  # Redis for caching
  redis:
    image: "redis:6-alpine"
    ports:
      - "6379:6379"

networks:
  default:
    name: smartdine-network

volumes:
  auth-postgres-data:
  payments-postgres-data:
  orders-postgres-data:
  menu-mongo-data: 