name: Frontend CI Workflow

on:
  push:
    branches:
      - frontend  # Trigger this workflow only on 'frontend' branch push
  pull_request:
    branches:
      - frontend  # Trigger on pull requests to 'frontend' branch

jobs:
  linting_and_testing:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your node version (adjust if needed)

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Prettier to format the code
      - name: Run Prettier
        run: npm run prettier --write .

      # Run linting
      - name: Run Lint
        run: npm run lint

      # Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run  # You may need to adjust this based on your Cypress script

  deploy:
    needs: linting_and_testing  # Ensure linting and tests are successful before deployment
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository again
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies again (if necessary for deployment)
      - name: Install dependencies
        run: npm install

      # Deploy to Vercel (make sure to set up your Vercel project for GitHub integration)
      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Set your Vercel token as a GitHub secret

