name: Next.js CI/CD Pipeline

on:
  push:
    branches:
      - frontend
  pull_request:
    branches:
      - frontend

jobs:
  build-and-lint:
    name: Build and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node 20, works great for Next.js

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Prettier Check
        run: npm run format:check

      - name: Next.js Build
        run: npm run build

  deploy:
    name: Deploy to Vercel
    needs: build-and-lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/frontend'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          prod: true